package io.rong.app.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_INFOS.
 */
public class UserInfos {

    private Long id;
    private String userid;
    private String username;
    private String portraits;
    private String status;

    public UserInfos() {
    }

    public UserInfos(Long id) {
        this.id = id;
    }

    public UserInfos(Long id, String userid, String username, String portraits, String status) {
        this.id = id;
        this.userid = userid;
        this.username = username;
        this.portraits = portraits;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPortraits() {
        return portraits;
    }

    public void setPortraits(String portraits) {
        this.portraits = portraits;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
